import { HStack } from "@chakra-ui/layout";
import { Divider } from "@chakra-ui/layout";
import { Text } from "@chakra-ui/layout";
import { Grid } from "@chakra-ui/layout";
import { VStack } from "@chakra-ui/layout";
import { Box, Flex } from "@chakra-ui/layout";
import Head from "next/head";
import ListItem from "../components/ListItem";

const Images = [
  { title: "Res", path: "/img/Res.jpg" },
  { title: "Bebidas", path: "/img/Bebidas.jpg" },
  { title: "Carnitas", path: "/img/Carnitas.jpg" },
  { title: "Cerdo", path: "/img/Bebidas.jpg" },
  { title: "Bebidas", path: "/img/Cerdo.jpg" },
  { title: "Embutidos", path: "/img/Embutidos.jpg" },
  { title: "Lacteos", path: "/img/Lacteos.jpg" },
  { title: "Maiz", path: "/img/Maiz.jpg" },
  { title: "Paquetes", path: "/img/Paquetes.jpg" },
  { title: "Pollo", path: "/img/Pollo.jpg" },
  { title: "Otros", path: "/img/Otros.jpg" },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Carniceria Gonzalez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        flexDir="column"
        w="100vw"
        maxW="100vw"
        overflow="hidden"
        minH="100vh"
      >
        <Grid bg="red" w="100%" h="20vh" maxH="128px" flexDir="column">
          <Text
            placeSelf="center"
            color="white"
            fontWeight="bold"
            textAlign="center"
            fontSize="24px"
          >
            CARNICERIA <br /> GONZALEZ
          </Text>
        </Grid>

        <Flex p="1rem" w="100%" flexDir="column">
          {Images.map(({ title, path }, index) => (
            <ListItem key={index} title={title} path={path} index={index} />
          ))}
        </Flex>
      </Flex>
    </>
  );
}
