import { Button } from "@chakra-ui/button";
import { useDisclosure } from "@chakra-ui/hooks";
import { Image } from "@chakra-ui/image";
import { Box, Flex } from "@chakra-ui/layout";
import { Collapse } from "@chakra-ui/transition";
import Head from "next/head";
import ListItem from "../components/ListItem";

const Images = [
  { title: "Res", path: "/img/Res.jpg" },
  { title: "Bebidas", path: "/img/Bebidas.jpg" },
  { title: "Carnitas", path: "/img/Carnitas.jpg" },
  { title: "Cerdo", path: "/img/Bebidas.jpg" },
  { title: "Bebidas", path: "/img/Cerdo.jpg" },
  { title: "Embutidos", path: "/img/Embutidos.jpg" },
  { title: "Lacteos", path: "/img/Lacteos.jpg" },
  { title: "Maiz", path: "/img/Maiz.jpg" },
  { title: "Paquetes", path: "/img/Paquetes.jpg" },
  { title: "Pollo", path: "/img/Pollo.jpg" },
  { title: "Otros", path: "/img/Otros.jpg" },
];

export default function Home() {
  const { isOpen, onToggle } = useDisclosure();
  return (
    <>
      <Head>
        <title>Carniceria Gonzalez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        flexDir="column"
        w="100vw"
        maxW="100vw"
        overflow="hidden"
        minH="100vh"
      >
        <Box bg="red" w="100%" h="20vh" maxH="128px"></Box>

        <Box p="1rem">
          {Images.map(({ title, path }, index) => (
            <ListItem key={index} title={title} path={path} />
          ))}
        </Box>
      </Flex>
    </>
  );
}
